# Generated by Django 3.2.9 on 2022-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_article_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, upload_to='Article-image/icon-image'),
        ),
    ]
