# Generated by Django 3.2.9 on 2022-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0006_alter_account_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to='Article-image'),
        ),
    ]
