# Generated by Django 3.2.9 on 2022-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0007_alter_account_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon_path',
            field=models.TextField(default=0, max_length=150),
        ),
    ]
